[project]
id = "demo-java-app"
name = "Java Firecracker Demo"

[[build.env]]
name = "BP_JVM_VERSION"
value = "17"

[[build.env]]
name = "BP_MAVEN_BUILD_ARGUMENTS"
value = "-Dquarkus.package.type=uber-jar package"
